# Site settings
title: "Natalia Wójcik"
description: "Natalia Wójcik's Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Natalia Wójcik"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "nataliaaawojcik@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "Oslo, Norway"

resume_header_contact_info:     "Oslo • nataliaaawojcik@gmail.com"
display_header_contact_info:    "true"

resume_header_intro:    "<p>I am a Software Engineer with 6 years of experience, focused on high-impact work within the Microsoft 365 backend. What drives me is the chance to solve tough problems—using a mix of analytical thinking and creativity to understand how systems work and how we can make them better. My interests span AI, scalable product architecture, and connecting with people to move ideas from concept to completion. With a background in Computer Science, I genuinely love the process of exploring new technologies and building robust solutions.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/natalia-oliwia-wojcik/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://wojciknatalia.github.io/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
